[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "$PORT"

# Railway会自动设置PORT环境变量
# 其他环境变量需要在Railway控制台中手动设置：
# - JWT_SECRET
# - DATABASE_URL (如果使用外部数据库)
# - MAX_FILE_SIZE
# - UPLOADS_DIR